import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "@/components/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test App for the Authentication and the trpc setup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Providers>
          <body
            className={cn(
              "min-h-screen antialiased font-sans grainy",
              inter.className
            )}
          >
            <Nav />
            {children}
          </body>
        </Providers>
      </html>
    </ClerkProvider>
  );
}
